/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package View;

/**
 *
 * @author nicolas
 */
public class Agenda extends javax.swing.JFrame {

    /**
     * Creates new form Agenda
     */
    public Agenda() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        textAgenda = new javax.swing.JLabel();
        botaoAgendar = new javax.swing.JButton();
        caixaObs = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        textObs = new javax.swing.JLabel();
        caixaTextId = new javax.swing.JTextField();
        textId = new javax.swing.JLabel();
        ComboBoxCliente = new javax.swing.JComboBox<>();
        textCliente = new javax.swing.JLabel();
        ComboBoxServico = new javax.swing.JComboBox<>();
        textServico1 = new javax.swing.JLabel();
        caixaTextValor = new javax.swing.JTextField();
        textValor = new javax.swing.JLabel();
        caixaTextData = new javax.swing.JTextField();
        textData = new javax.swing.JLabel();
        caixaTextHora = new javax.swing.JTextField();
        textHora = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        painelAgenda = new javax.swing.JLabel();
        agendaFundo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        textAgenda.setFont(new java.awt.Font("Dialog", 1, 36)); // NOI18N
        textAgenda.setForeground(new java.awt.Color(255, 255, 255));
        textAgenda.setText("Agenda");
        getContentPane().add(textAgenda, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 80, 170, 50));

        botaoAgendar.setBackground(new java.awt.Color(102, 204, 0));
        botaoAgendar.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        botaoAgendar.setForeground(new java.awt.Color(255, 255, 255));
        botaoAgendar.setText("Agendar");
        getContentPane().add(botaoAgendar, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 550, 390, 50));

        caixaObs.setBackground(new java.awt.Color(255, 255, 255));
        caixaObs.setForeground(new java.awt.Color(0, 0, 0));

        jTextArea1.setBackground(new java.awt.Color(255, 255, 255));
        jTextArea1.setColumns(20);
        jTextArea1.setForeground(new java.awt.Color(0, 0, 0));
        jTextArea1.setRows(5);
        caixaObs.setViewportView(jTextArea1);

        getContentPane().add(caixaObs, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 210, 390, 320));

        textObs.setFont(new java.awt.Font("Dialog", 1, 36)); // NOI18N
        textObs.setForeground(new java.awt.Color(255, 255, 255));
        textObs.setText("Observacões");
        getContentPane().add(textObs, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 150, 260, 50));

        caixaTextId.setBackground(new java.awt.Color(255, 255, 255));
        caixaTextId.setForeground(new java.awt.Color(0, 0, 0));
        caixaTextId.setText("0");
        caixaTextId.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                caixaTextIdActionPerformed(evt);
            }
        });
        getContentPane().add(caixaTextId, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 170, 270, 40));

        textId.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        textId.setForeground(new java.awt.Color(255, 255, 255));
        textId.setText("Id:");
        getContentPane().add(textId, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 180, 40, 20));

        ComboBoxCliente.setBackground(new java.awt.Color(255, 255, 255));
        ComboBoxCliente.setForeground(new java.awt.Color(0, 0, 0));
        ComboBoxCliente.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Corte", "Barba", "Sobrancelha", "Relaxamento", " " }));
        ComboBoxCliente.setToolTipText("");
        getContentPane().add(ComboBoxCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 310, 270, 40));

        textCliente.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        textCliente.setForeground(new java.awt.Color(255, 255, 255));
        textCliente.setText("Cliente:");
        getContentPane().add(textCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 250, 110, 20));

        ComboBoxServico.setBackground(new java.awt.Color(255, 255, 255));
        ComboBoxServico.setForeground(new java.awt.Color(0, 0, 0));
        ComboBoxServico.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Ana", "Pedro", "Rapha", "Nicolas", " " }));
        ComboBoxServico.setToolTipText("");
        getContentPane().add(ComboBoxServico, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 240, 270, 40));

        textServico1.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        textServico1.setForeground(new java.awt.Color(255, 255, 255));
        textServico1.setText("Servico:");
        getContentPane().add(textServico1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 320, 110, 20));

        caixaTextValor.setBackground(new java.awt.Color(255, 255, 255));
        caixaTextValor.setForeground(new java.awt.Color(0, 0, 0));
        caixaTextValor.setText("0");
        caixaTextValor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                caixaTextValorActionPerformed(evt);
            }
        });
        getContentPane().add(caixaTextValor, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 390, 270, 40));

        textValor.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        textValor.setForeground(new java.awt.Color(255, 255, 255));
        textValor.setText("Valor R$:");
        getContentPane().add(textValor, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 400, 110, 20));

        caixaTextData.setBackground(new java.awt.Color(255, 255, 255));
        caixaTextData.setForeground(new java.awt.Color(0, 0, 0));
        caixaTextData.setText("0");
        caixaTextData.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                caixaTextDataActionPerformed(evt);
            }
        });
        getContentPane().add(caixaTextData, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 460, 270, 40));

        textData.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        textData.setForeground(new java.awt.Color(255, 255, 255));
        textData.setText("Data:");
        getContentPane().add(textData, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 470, 70, 20));

        caixaTextHora.setBackground(new java.awt.Color(255, 255, 255));
        caixaTextHora.setForeground(new java.awt.Color(0, 0, 0));
        caixaTextHora.setText("0");
        caixaTextHora.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                caixaTextHoraActionPerformed(evt);
            }
        });
        getContentPane().add(caixaTextHora, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 530, 270, 40));

        textHora.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        textHora.setForeground(new java.awt.Color(255, 255, 255));
        textHora.setText("Hora:");
        getContentPane().add(textHora, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 540, 70, 20));

        jTable1.setBackground(new java.awt.Color(204, 204, 204));
        jTable1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jTable1.setForeground(new java.awt.Color(0, 0, 0));
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"1", "Alan", "Barba", "20"},
                {"2", "Nicolas", "Corte", "15"},
                {"3", "Ana", "Maquiagem", "30"},
                {null, null, null, null}
            },
            new String [] {
                "Id", "Cliente", "Servicos", "Valor"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 630, 1000, 290));

        painelAgenda.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/Agenda-PainelFundo.png"))); // NOI18N
        getContentPane().add(painelAgenda, new org.netbeans.lib.awtextra.AbsoluteConstraints(-10, -10, -1, -1));

        agendaFundo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/AgendaFundo.png"))); // NOI18N
        getContentPane().add(agendaFundo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void caixaTextIdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_caixaTextIdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_caixaTextIdActionPerformed

    private void caixaTextValorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_caixaTextValorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_caixaTextValorActionPerformed

    private void caixaTextHoraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_caixaTextHoraActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_caixaTextHoraActionPerformed

    private void caixaTextDataActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_caixaTextDataActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_caixaTextDataActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Agenda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Agenda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Agenda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Agenda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Agenda().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> ComboBoxCliente;
    private javax.swing.JComboBox<String> ComboBoxServico;
    private javax.swing.JLabel agendaFundo;
    private javax.swing.JButton botaoAgendar;
    private javax.swing.JScrollPane caixaObs;
    private javax.swing.JTextField caixaTextData;
    private javax.swing.JTextField caixaTextHora;
    private javax.swing.JTextField caixaTextId;
    private javax.swing.JTextField caixaTextValor;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JLabel painelAgenda;
    private javax.swing.JLabel textAgenda;
    private javax.swing.JLabel textCliente;
    private javax.swing.JLabel textData;
    private javax.swing.JLabel textHora;
    private javax.swing.JLabel textId;
    private javax.swing.JLabel textObs;
    private javax.swing.JLabel textServico1;
    private javax.swing.JLabel textValor;
    // End of variables declaration//GEN-END:variables
}
