/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package View;

/**
 *
 * @author nicolas
 */
public class Login extends javax.swing.JFrame {

    /**
     * Creates new form Login
     */
    public Login() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        caixaTextUsuario = new javax.swing.JTextField();
        caixaTextSenha = new javax.swing.JPasswordField();
        textSenha = new javax.swing.JLabel();
        textUsuario = new javax.swing.JLabel();
        textLogin = new javax.swing.JLabel();
        painelLogin = new javax.swing.JLabel();
        fundoTela = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        caixaTextUsuario.setForeground(new java.awt.Color(255, 255, 255));
        getContentPane().add(caixaTextUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 490, 170, 40));

        caixaTextSenha.setForeground(new java.awt.Color(255, 255, 255));
        caixaTextSenha.setToolTipText("");
        getContentPane().add(caixaTextSenha, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 630, 170, 40));

        textSenha.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        textSenha.setForeground(new java.awt.Color(255, 255, 255));
        textSenha.setText("Senha");
        getContentPane().add(textSenha, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 560, 90, 60));

        textUsuario.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        textUsuario.setForeground(new java.awt.Color(255, 255, 255));
        textUsuario.setText("Usuário");
        getContentPane().add(textUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 430, 90, 60));

        textLogin.setFont(new java.awt.Font("Dialog", 1, 36)); // NOI18N
        textLogin.setForeground(new java.awt.Color(255, 255, 255));
        textLogin.setText("Login");
        getContentPane().add(textLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 340, 120, 60));

        painelLogin.setIcon(new javax.swing.ImageIcon("/home/nicolas/ProjetosJava/BarberShop/src/main/java/imagens/painel-login.png")); // NOI18N
        getContentPane().add(painelLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 310, -1, -1));

        fundoTela.setIcon(new javax.swing.ImageIcon("/home/nicolas/ProjetosJava/BarberShop/src/main/java/imagens/Logo.jpg")); // NOI18N
        getContentPane().add(fundoTela, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPasswordField caixaTextSenha;
    private javax.swing.JTextField caixaTextUsuario;
    private javax.swing.JLabel fundoTela;
    private javax.swing.JLabel painelLogin;
    private javax.swing.JLabel textLogin;
    private javax.swing.JLabel textSenha;
    private javax.swing.JLabel textUsuario;
    // End of variables declaration//GEN-END:variables
}
